import type { NewsArticle } from '../types'

const now = new Date()
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString()

export const MOCK_LOCAL_NEWS: NewsArticle[] = [
  {
    id: 'local-1',
    title: 'Dindigul District Sees Record Investment in Textile Industry',
    description: 'A consortium of investors has announced a ₹500 crore investment in the Dindigul textile sector, promising 10,000 new jobs for the region.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format',
    source: { name: 'The Hindu' },
    publishedAt: hoursAgo(1),
    category: 'business',
    location: { city: 'Dindigul', state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
  {
    id: 'local-2',
    title: 'Tamil Nadu CM Inaugurates New Highway Connecting Madurai to Dindigul',
    description: 'The 4-lane expressway will cut travel time between the two cities to under 45 minutes, boosting trade and tourism.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=800&q=80&auto=format',
    source: { name: 'Times of India' },
    publishedAt: hoursAgo(3),
    category: 'general',
    location: { city: 'Dindigul', state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
  {
    id: 'local-3',
    title: 'Farmers in Dindigul Adopt AI-Powered Irrigation Systems',
    description: 'Local agricultural cooperatives partner with an IIT Madras startup to deploy smart drip irrigation across 2,000 acres.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80&auto=format',
    source: { name: 'Deccan Chronicle' },
    publishedAt: hoursAgo(5),
    category: 'technology',
    location: { city: 'Dindigul', state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
  {
    id: 'local-4',
    title: 'Tamil Nadu Police to Deploy AI Surveillance in 5 Districts',
    description: 'The state government announces a ₹120 crore AI-powered surveillance network covering Dindigul, Madurai, Coimbatore, Chennai, and Salem.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80&auto=format',
    source: { name: 'The Hindu' },
    publishedAt: hoursAgo(7),
    category: 'technology',
    location: { state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
  {
    id: 'local-5',
    title: 'Dindigul Lock Factory Workers Get 20% Wage Hike After Negotiations',
    description: 'After a week-long standoff, the management of Dindigul\'s iconic lock manufacturing clusters agreed to raise wages for 8,000 workers.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=800&q=80&auto=format',
    source: { name: 'Indian Express' },
    publishedAt: hoursAgo(9),
    category: 'economy',
    location: { city: 'Dindigul', state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
  {
    id: 'local-6',
    title: 'New Medical College to Open in Dindigul by 2026',
    description: 'The Tamil Nadu government has approved construction of a 200-bed MBBS college to address the growing healthcare needs of the southern district.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80&auto=format',
    source: { name: 'New Indian Express' },
    publishedAt: hoursAgo(12),
    category: 'health',
    location: { city: 'Dindigul', state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
  {
    id: 'local-7',
    title: 'Palani Murugan Temple Records 5 Lakh Pilgrims on Panguni Uthiram',
    description: 'Devotees from Tamil Nadu and across India flocked to Palani for the annual festival, breaking all previous records.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1583394293214-0ef4e9375e14?w=800&q=80&auto=format',
    source: { name: 'Dinamalar' },
    publishedAt: hoursAgo(15),
    category: 'general',
    location: { city: 'Dindigul', state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
  {
    id: 'local-8',
    title: 'TN Government Launches Free Coding Bootcamp for Rural Students in Dindigul',
    description: 'A first-of-its-kind initiative will train 5,000 students from government schools in Python, web development, and data science over 6 months.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1509966756634-9c23dd6e6815?w=800&q=80&auto=format',
    source: { name: 'Deccan Herald' },
    publishedAt: hoursAgo(20),
    category: 'education',
    location: { city: 'Dindigul', state: 'Tamil Nadu', country: 'India' },
    type: 'local',
  },
]

export const MOCK_GLOBAL_NEWS: NewsArticle[] = [
  {
    id: 'global-1',
    title: 'OpenAI Releases GPT-5 with Unprecedented Reasoning Capabilities',
    description: 'The new model can solve complex multi-step problems across science, law, and medicine with near-human accuracy.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80&auto=format',
    source: { name: 'TechCrunch' },
    publishedAt: hoursAgo(2),
    category: 'ai',
    type: 'global',
  },
  {
    id: 'global-2',
    title: 'India Wins Cricket World Cup in a Thrilling Final Against Australia',
    description: 'Rohit Sharma\'s century led India to a stunning 6-wicket victory in the ICC Cricket World Cup final at Wankhede Stadium.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?w=800&q=80&auto=format',
    source: { name: 'ESPN Cricinfo' },
    publishedAt: hoursAgo(4),
    category: 'sports',
    type: 'global',
  },
  {
    id: 'global-3',
    title: 'SpaceX Starship Successfully Completes First Crewed Mission to Orbit',
    description: 'Four astronauts spent 6 hours in orbit aboard the fully reusable Starship, marking a historic milestone in commercial spaceflight.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?w=800&q=80&auto=format',
    source: { name: 'Space.com' },
    publishedAt: hoursAgo(6),
    category: 'space',
    type: 'global',
  },
  {
    id: 'global-4',
    title: 'Global Markets Rally as US Fed Signals Rate Cuts for 2025',
    description: 'Stock markets across Asia, Europe, and the Americas surged after the Fed chair hinted at three rate cuts in the upcoming year.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80&auto=format',
    source: { name: 'Bloomberg' },
    publishedAt: hoursAgo(8),
    category: 'finance',
    type: 'global',
  },
  {
    id: 'global-5',
    title: 'Scientists Discover New Antibiotic That Kills Drug-Resistant Bacteria',
    description: 'Researchers at MIT announce a breakthrough compound that effectively eliminates MRSA and other superbugs in clinical trials.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80&auto=format',
    source: { name: 'Nature' },
    publishedAt: hoursAgo(10),
    category: 'health',
    type: 'global',
  },
  {
    id: 'global-6',
    title: 'Apple Unveils AR Glasses with All-Day Battery Life at WWDC',
    description: 'The long-awaited Apple Vision Lite features lightweight frames, a new display chip, and 12 hours of battery — priced at $1,499.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=800&q=80&auto=format',
    source: { name: 'The Verge' },
    publishedAt: hoursAgo(14),
    category: 'technology',
    type: 'global',
  },
  {
    id: 'global-7',
    title: 'Netflix Breaks Subscriber Records with Bollywood Blockbuster',
    description: 'The platform gains 15 million new subscribers in a single weekend after releasing an Indian-language thriller that broke viewership records.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&q=80&auto=format',
    source: { name: 'Variety' },
    publishedAt: hoursAgo(18),
    category: 'entertainment',
    type: 'global',
  },
  {
    id: 'global-8',
    title: 'ISRO Successfully Launches Chandrayaan-4 with Sample Return Mission',
    description: 'India\'s fourth lunar mission aims to collect 2kg of lunar soil and return it to Earth — a feat achieved by only two other nations.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800&q=80&auto=format',
    source: { name: 'NDTV' },
    publishedAt: hoursAgo(22),
    category: 'space',
    type: 'global',
  },
  {
    id: 'global-9',
    title: 'India\'s GDP Grows at 8.4% — Fastest Among G20 Nations',
    description: 'The World Bank revises India\'s growth forecast upward, citing strong manufacturing output and record FDI inflows.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&q=80&auto=format',
    source: { name: 'Economic Times' },
    publishedAt: hoursAgo(26),
    category: 'economy',
    type: 'global',
  },
  {
    id: 'global-10',
    title: 'Google DeepMind\'s AI Solves 50-Year-Old Protein Folding Challenge',
    description: 'AlphaFold 3 predicts molecular interactions with atomic precision, opening doors to personalized medicine and drug discovery.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1628595351029-c2bf17511435?w=800&q=80&auto=format',
    source: { name: 'Wired' },
    publishedAt: hoursAgo(30),
    category: 'science',
    type: 'global',
  },
  {
    id: 'global-11',
    title: 'Tesla Cybertruck Sets Record for Fastest EV Cross-Country Trip',
    description: 'A Cybertruck completed the US coast-to-coast drive in under 40 hours, with only 4 charging stops averaging 18 minutes each.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800&q=80&auto=format',
    source: { name: 'Electrek' },
    publishedAt: hoursAgo(35),
    category: 'automotive',
    type: 'global',
  },
  {
    id: 'global-12',
    title: 'Indian Startup Ecosystem Raises $10 Billion in H1 2025',
    description: 'Venture capital flows into Indian startups hit a record high, led by fintech, healthtech, and agritech sectors.',
    url: '#',
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80&auto=format',
    source: { name: 'Inc42' },
    publishedAt: hoursAgo(40),
    category: 'startups',
    type: 'global',
  },
]
